config/routes.rb
Beyondlife::Application.routes.draw do
  root :to => 'static#index'

  get '/sign_in' => 'sessions#new', :as => 'sign_in'
  get '/sessions' => 'sessions#create', :as => 'sessions'
  get '/sign_out' => 'sessions#destroy', :as => 'sign_out'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')

  get '/guest_posts/new', controller: 'guest_posts', action: 'new', as: 'new_guest_post'
  post '/guest_posts', controller: 'guest_posts', action: 'create'

  get '/guest_posts', controller: 'guest_posts', action: 'index', as: 'guest_posts'
  get '/guest_posts/:id', controller: 'guest_posts', action: 'show', as: 'guest_post'

  get '/guest_posts/:id/edit', controller: 'guest_posts', action: 'edit', as: 'edit_guest_post'
  put '/guest_posts/:id', controller: 'guest_posts', action: 'update'

  delete '/guest_posts/:id', controller: 'guest_posts', action: 'destroy'

  get '/trait_types/new', controller: 'trait_types', action: 'new', as: 'new_trait_type'
  post '/trait_types', controller: 'trait_types', action: 'create'

  get '/trait_types', controller: 'trait_types', action: 'index', as: 'trait_types'
  get '/trait_types/:id', controller: 'trait_types', action: 'show', as: 'trait_type'

  get '/trait_types/:id/edit', controller: 'trait_types', action: 'edit', as: 'edit_trait_type'
  put '/trait_types/:id', controller: 'trait_types', action: 'update'

  delete '/trait_types/:id', controller: 'trait_types', action: 'destroy'

  get '/traits/new', controller: 'traits', action: 'new', as: 'new_trait'
  post '/traits', controller: 'traits', action: 'create'

  get '/traits', controller: 'traits', action: 'index', as: 'traits'
  get '/traits/:id', controller: 'traits', action: 'show', as: 'trait'

  get '/traits/:id/edit', controller: 'traits', action: 'edit', as: 'edit_trait'
  put '/traits/:id', controller: 'traits', action: 'update'

  delete '/traits/:id', controller: 'traits', action: 'destroy'

  get '/people/new', controller: 'people', action: 'new', as: 'new_person'
  post '/people', controller: 'people', action: 'create'

  get '/people', controller: 'people', action: 'index', as: 'people'
  get '/people/:id', controller: 'people', action: 'show', as: 'person'

  get '/people/:id/edit', controller: 'people', action: 'edit', as: 'edit_person'
  put '/people/:id', controller: 'people', action: 'update'

  delete '/people/:id', controller: 'people', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :user
  has_many :trait_types, :through => :traits
  has_many :guest_posts

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def index
    @people = Person.all
  end

  def show
    @person = Person.find_by_id(params[:id])
  end

  def new
    @user = User.find(session[:user_id])
    @person = Person.new
  end

  def create
    @person = Person.new
    @person.dob = params[:dob]
    @person.dod = params[:dod]
    @person.full_name = params[:full_name]
    @person.quote = params[:quote]
    @person.eulogy = params[:eulogy]
    @person.charity = params[:charity]
    @person.photo_url = params[:photo_url]

    if @person.save
            redirect_to person_url(Person.last)
          else
      render 'new'
    end
  end

  def edit
    @person = Person.find_by_id(params[:id])
  end

  def update
    @person = Person.find_by_id(params[:id])
    @person.dob = params[:dob]
    @person.dod = params[:dod]
    @person.full_name = params[:full_name]
    @person.quote = params[:quote]
    @person.eulogy = params[:eulogy]
    @person.charity = params[:charity]
    @person.photo_url = params[:photo_url]

    if @person.save
            redirect_to people_url
          else
      render 'edit'
    end
  end

  def destroy
    @person = Person.find_by_id(params[:id])
    @person.destroy
        redirect_to people_url
      end
end

app/views/people/edit.html.erb
<h1>Editing Person #<%= @person.id %></h1>


<%= form_tag(person_url(@person), method: 'put') do %>

  <div>
    <%= label_tag :dob %><br />
    <%= datetime_select_tag :dob, @person.dob %>
  </div>

  <div>
    <%= label_tag :dod %><br />
    <%= datetime_select_tag :dod, @person.dod %>
  </div>

  <div>
    <%= label_tag :full_name %><br />
    <%= text_field_tag :full_name, @person.full_name %>
  </div>

  <div>
    <%= label_tag :quote %><br />
    <%= text_field_tag :quote, @person.quote %>
  </div>

  <div>
    <%= label_tag :eulogy %><br />
    <%= text_field_tag :eulogy, @person.eulogy %>
  </div>

  <div>
    <%= label_tag :charity %><br />
    <%= text_field_tag :charity, @person.charity %>
  </div>

  <div>
    <%= label_tag :photo_url %><br />
    <%= text_field_tag :photo_url, @person.photo_url %>
  </div>

  
  <div>
    <%= submit_tag "Update Person" %>
  </div>

<% end %>

app/views/people/index.html.erb
<h1>My Tributes</h1>

<h4><%= link_to 'Add a New Person', new_person_url %></h4>

<% @people.each do |person| %>
      <div class="hero-unit">
        <div class="media">
          <a class="pull-left">
            <%= image_tag person.photo_url, :class => "media-object img-circle index-img-circle" %>
          </a>
          <div class="media-body">
            <h2 class="media-heading"><%= link_to person.full_name, person %></h2>
            <p><%= person.dob %> to <%= person.dod %></p>
            <div class="media">
                <h4>
                  <%= image_tag "iconmonstr-quote-5-icon.png", :class => "quote-icon" %> <%= person.quote %>
                  <%= image_tag "iconmonstr-quote-6-icon.png", :class => "quote-icon" %>
                </h4>
              <%= link_to image_tag("iconmonstr-eye-6-icon.png", :class => 'edit-button'), person_url(person.id) %>
              <%= link_to image_tag("iconmonstr-edit-9-icon.png", :class => 'edit-button'), edit_person_url(person.id) %>
              <%= link_to image_tag("iconmonstr-trash-can-15-icon.png", :class => 'edit-button'), person_url(person.id), :method => 'delete', data: { confirm: "Do you really want to delete this post?" } %>


            </div>
          </div>
        </div>
      </div>
<% end %>

app/views/people/new.html.erb
<h1 class="span8 offset2">Add a new Tribute.</h1>


<%= form_tag(people_url, method: 'post', :class => 'clearfix form-horizontal span6 offset2') do %>

  <%= hidden_field_tag :user_id, @user.id %>

  <div class="control-group">
    <%= label_tag :dob, "Date of Birth", :class => "control-label" %>
      <div class="controls">
        <%= text_field_tag :dob %> <br />
      </div>
  </div>

  <div class="control-group">
    <%= label_tag :dod, "Date of Death", :class => "control-label" %>
      <div class="controls">
        <%= text_field_tag :dod %> <br />
      </div>
  </div>

  <div class="control-group">
    <%= label_tag :full_name, "Full Name", :class => "control-label" %>
      <div class="controls">
        <%= text_field_tag :full_name %> <br />
      </div>
  </div>

  <div class="control-group">
    <%= label_tag :quote, "Remembrance Quote", :class => "control-label" %>
      <div class="controls">
        <%= text_area_tag :quote %> <br />
      </div>
  </div>

  <div class="control-group">
    <%= label_tag :eulogy, "Eulogy", :class => "control-label" %>
      <div class="controls">
        <%= text_area_tag :eulogy %> <br />
      </div>
  </div>

  <div class="control-group">
    <%= label_tag :charity, "Charity (optional)", :class => "control-label" %>
      <div class="controls">
        <%= text_field_tag :charity %> <br />
      </div>
  </div>

  <div class="control-group">
    <%= label_tag :photo_url, "Image URL", :class => "control-label" %>
      <div class="controls">
        <%= text_field_tag :photo_url %> <br />
      </div>
  </div>

    <div>
      <button type="submit" class="btn btn-primary span2 offset2">Create Tribute</button>
    </div>
<% end %>

app/views/people/show.html.erb
<div class="left-col">
  <%= image_tag @person.photo_url %>
</div>

<div class="right-col">
  <h1><%= @person.full_name %></h1>
  <h5><%= @person.dob %> - <%= @person.dod %></h5>

<h4>
  <%= image_tag "iconmonstr-quote-5-icon.png", :class => "quote-icon" %> <%= @person.quote %>
  <%= image_tag "iconmonstr-quote-6-icon.png", :class => "quote-icon" %>
</h4>

<p>
  <b>Eulogy:</b>
  <%= @person.eulogy %>
</p>

<p>
  <b>Charity:</b>
  <%= @person.charity %>
</p>

</div>

<div class="guest_post_container clearfix">
  <div class="button-header">
      <% if session[:user_id].present? %>
          <a href="<%= new_guest_post_url %>?person_id=<%= @person.id %>"><button class="btn btn-primary btn-large span3">Add a Guest Post</button></a>
      <% else %>
        <a href="/auth/facebook"><button class="btn btn-primary btn-large span3 offset2">Sign in via Facebook</button></a>
      <% end %>
  </div>

    <% @person.guest_posts.each do |post| %>
      <div class="clearfix hero-unit">
        <div class="media">
          <a class="pull-left">
            <%= image_tag post.user.avatar, :class => "media-object img-circle" %>
          </a>
          <div class="media-body">
            <h4 class="media-heading"><%= post.user.full_name %></h4>
            <div class="media">
              <% if post.text.length >= 1 %>
                <p>"<%= post.text %>"</p>
              <% else %>
                <br />
              <% end %>
              <h5><%= distance_of_time_in_words(post.created_at, to_time = Time.now, include_seconds = false) %> ago
              <%= link_to image_tag("iconmonstr-trash-can-15-icon.png", :class => 'right edit-button'), guest_post_url(post.id), :method => 'delete', data: { confirm: "Do you really want to delete this post?" } %>
              <%= link_to image_tag("iconmonstr-edit-9-icon.png", :class => 'right edit-button'), edit_guest_post_url(post.id) %>
              </h5>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>