config/routes.rb
Beyondlife::Application.routes.draw do
  root :to => 'static#index'

  get '/sign_in' => 'sessions#new', :as => 'sign_in'
  get '/sessions' => 'sessions#create', :as => 'sessions'
  get '/sign_out' => 'sessions#destroy', :as => 'sign_out'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')

  get '/guest_posts/new', controller: 'guest_posts', action: 'new', as: 'new_guest_post'
  post '/guest_posts', controller: 'guest_posts', action: 'create'

  get '/guest_posts', controller: 'guest_posts', action: 'index', as: 'guest_posts'
  get '/guest_posts/:id', controller: 'guest_posts', action: 'show', as: 'guest_post'

  get '/guest_posts/:id/edit', controller: 'guest_posts', action: 'edit', as: 'edit_guest_post'
  put '/guest_posts/:id', controller: 'guest_posts', action: 'update'

  delete '/guest_posts/:id', controller: 'guest_posts', action: 'destroy'

  get '/trait_types/new', controller: 'trait_types', action: 'new', as: 'new_trait_type'
  post '/trait_types', controller: 'trait_types', action: 'create'

  get '/trait_types', controller: 'trait_types', action: 'index', as: 'trait_types'
  get '/trait_types/:id', controller: 'trait_types', action: 'show', as: 'trait_type'

  get '/trait_types/:id/edit', controller: 'trait_types', action: 'edit', as: 'edit_trait_type'
  put '/trait_types/:id', controller: 'trait_types', action: 'update'

  delete '/trait_types/:id', controller: 'trait_types', action: 'destroy'

  get '/traits/new', controller: 'traits', action: 'new', as: 'new_trait'
  post '/traits', controller: 'traits', action: 'create'

  get '/traits', controller: 'traits', action: 'index', as: 'traits'
  get '/traits/:id', controller: 'traits', action: 'show', as: 'trait'

  get '/traits/:id/edit', controller: 'traits', action: 'edit', as: 'edit_trait'
  put '/traits/:id', controller: 'traits', action: 'update'

  delete '/traits/:id', controller: 'traits', action: 'destroy'

  get '/people/new', controller: 'people', action: 'new', as: 'new_person'
  post '/people', controller: 'people', action: 'create'

  get '/people', controller: 'people', action: 'index', as: 'people'
  get '/people/:id', controller: 'people', action: 'show', as: 'person'

  get '/people/:id/edit', controller: 'people', action: 'edit', as: 'edit_person'
  put '/people/:id', controller: 'people', action: 'update'

  delete '/people/:id', controller: 'people', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/trait.rb
class Trait < ActiveRecord::Base
  belongs_to :person
  belongs_to :trait_type
end

app/models/trait_type.rb
class TraitType < ActiveRecord::Base
  has_many :people, :through => :traits
end

app/controllers/traits_controller.rb
class TraitsController < ApplicationController

  def index
    @traits = Trait.all
  end

  def show
    @trait = Trait.find_by_id(params[:id])
  end

  def new
    @trait = Trait.new
  end

  def create
    @trait = Trait.new
    @trait.person_id = params[:person_id]
    @trait.trait_type_id = params[:trait_type_id]
    
    if @trait.save
            redirect_to traits_url
          else
      render 'new'
    end
  end

  def edit
    @trait = Trait.find_by_id(params[:id])
  end

  def update
    @trait = Trait.find_by_id(params[:id])
    @trait.person_id = params[:person_id]
    @trait.trait_type_id = params[:trait_type_id]
    
    if @trait.save
            redirect_to traits_url
          else
      render 'edit'
    end
  end

  def destroy
    @trait = Trait.find_by_id(params[:id])
    @trait.destroy
        redirect_to traits_url
      end
end

app/views/traits/edit.html.erb
<h1>Editing Trait #<%= @trait.id %></h1>


<%= form_tag(trait_url(@trait), method: 'put') do %>

  <div>
    <%= label_tag :person_id %><br />
    <%= number_field_tag :person_id, @trait.person_id %>
  </div>

  <div>
    <%= label_tag :trait_type_id %><br />
    <%= number_field_tag :trait_type_id, @trait.trait_type_id %>
  </div>

  
  <div>
    <%= submit_tag "Update Trait" %>
  </div>

<% end %>

app/views/traits/index.html.erb
<h1>Traits</h1>

<p><%= link_to 'Add a New Trait', new_trait_url %></p>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Trait type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @traits.each do |trait| %>
    <tr>
      <td><%= trait.person_id %></td>
      <td><%= trait.trait_type_id %></td>
  
      <td><%= link_to 'Show', trait_url(trait) %></td>
      <td><%= link_to 'Edit', edit_trait_url(trait) %></td>
      <td><%= link_to 'Destroy', trait_url(trait), method: 'delete', data: { confirm: "Do you really want to delete this trait?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/traits/new.html.erb
<h1>New Trait</h1>


<%= form_tag(traits_url, method: 'post') do %>


  <div>
    <%= label_tag :person_id %><br />
    <%= number_field_tag :person_id %>
  </div>

    <div>
    <%= label_tag :trait_type_id %><br />
    <%= number_field_tag :trait_type_id %>
  </div>

  
  <div>
    <%= submit_tag "Create Trait" %>
  </div>
<% end %>

app/views/traits/show.html.erb
<h1>Trait #<%= @trait.id %></h1>

<p>
  <b>Person:</b>
  <%= @trait.person_id %>
</p>

<p>
  <b>Trait type:</b>
  <%= @trait.trait_type_id %>
</p>