config/routes.rb
Beyondlife::Application.routes.draw do
  root :to => 'static#index'

  get '/sign_in' => 'sessions#new', :as => 'sign_in'
  get '/sessions' => 'sessions#create', :as => 'sessions'
  get '/sign_out' => 'sessions#destroy', :as => 'sign_out'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')

  get '/guest_posts/new', controller: 'guest_posts', action: 'new', as: 'new_guest_post'
  post '/guest_posts', controller: 'guest_posts', action: 'create'

  get '/guest_posts', controller: 'guest_posts', action: 'index', as: 'guest_posts'
  get '/guest_posts/:id', controller: 'guest_posts', action: 'show', as: 'guest_post'

  get '/guest_posts/:id/edit', controller: 'guest_posts', action: 'edit', as: 'edit_guest_post'
  put '/guest_posts/:id', controller: 'guest_posts', action: 'update'

  delete '/guest_posts/:id', controller: 'guest_posts', action: 'destroy'

  get '/trait_types/new', controller: 'trait_types', action: 'new', as: 'new_trait_type'
  post '/trait_types', controller: 'trait_types', action: 'create'

  get '/trait_types', controller: 'trait_types', action: 'index', as: 'trait_types'
  get '/trait_types/:id', controller: 'trait_types', action: 'show', as: 'trait_type'

  get '/trait_types/:id/edit', controller: 'trait_types', action: 'edit', as: 'edit_trait_type'
  put '/trait_types/:id', controller: 'trait_types', action: 'update'

  delete '/trait_types/:id', controller: 'trait_types', action: 'destroy'

  get '/traits/new', controller: 'traits', action: 'new', as: 'new_trait'
  post '/traits', controller: 'traits', action: 'create'

  get '/traits', controller: 'traits', action: 'index', as: 'traits'
  get '/traits/:id', controller: 'traits', action: 'show', as: 'trait'

  get '/traits/:id/edit', controller: 'traits', action: 'edit', as: 'edit_trait'
  put '/traits/:id', controller: 'traits', action: 'update'

  delete '/traits/:id', controller: 'traits', action: 'destroy'

  get '/people/new', controller: 'people', action: 'new', as: 'new_person'
  post '/people', controller: 'people', action: 'create'

  get '/people', controller: 'people', action: 'index', as: 'people'
  get '/people/:id', controller: 'people', action: 'show', as: 'person'

  get '/people/:id/edit', controller: 'people', action: 'edit', as: 'edit_person'
  put '/people/:id', controller: 'people', action: 'update'

  delete '/people/:id', controller: 'people', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/controllers/trait_types_controller.rb
class TraitTypesController < ApplicationController

  def index
    @trait_types = TraitType.all
  end

  def show
    @trait_type = TraitType.find_by_id(params[:id])
  end

  def new
    @trait_type = TraitType.new
  end

  def create
    @trait_type = TraitType.new
    @trait_type.name = params[:name]
    @trait_type.image_url = params[:image_url]
    @trait_type.description = params[:description]
    
    if @trait_type.save
            redirect_to trait_types_url
          else
      render 'new'
    end
  end

  def edit
    @trait_type = TraitType.find_by_id(params[:id])
  end

  def update
    @trait_type = TraitType.find_by_id(params[:id])
    @trait_type.name = params[:name]
    @trait_type.image_url = params[:image_url]
    @trait_type.description = params[:description]
    
    if @trait_type.save
            redirect_to trait_types_url
          else
      render 'edit'
    end
  end

  def destroy
    @trait_type = TraitType.find_by_id(params[:id])
    @trait_type.destroy
        redirect_to trait_types_url
      end
end

app/views/trait_types/edit.html.erb
<h1>Editing Trait Type #<%= @trait_type.id %></h1>


<%= form_tag(trait_type_url(@trait_type), method: 'put') do %>

  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name, @trait_type.name %>
  </div>

  <div>
    <%= label_tag :image_url %><br />
    <%= text_field_tag :image_url, @trait_type.image_url %>
  </div>

  <div>
    <%= label_tag :description %><br />
    <%= text_field_tag :description, @trait_type.description %>
  </div>

  
  <div>
    <%= submit_tag "Update Trait Type" %>
  </div>

<% end %>

app/views/trait_types/index.html.erb
<h1>Trait types</h1>

<p><%= link_to 'Add a New Trait Type', new_trait_type_url %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image url</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @trait_types.each do |trait_type| %>
    <tr>
      <td><%= trait_type.name %></td>
      <td><%= trait_type.image_url %></td>
      <td><%= trait_type.description %></td>
  
      <td><%= link_to 'Show', trait_type_url(trait_type) %></td>
      <td><%= link_to 'Edit', edit_trait_type_url(trait_type) %></td>
      <td><%= link_to 'Destroy', trait_type_url(trait_type), method: 'delete', data: { confirm: "Do you really want to delete this trait_type?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/trait_types/new.html.erb
<h1>New Trait Type</h1>


<%= form_tag(trait_types_url, method: 'post') do %>


  <div>
    <%= label_tag :name %><br />
    <%= text_field_tag :name %>
  </div>

    <div>
    <%= label_tag :image_url %><br />
    <%= text_field_tag :image_url %>
  </div>

    <div>
    <%= label_tag :description %><br />
    <%= text_field_tag :description %>
  </div>

  
  <div>
    <%= submit_tag "Create Trait Type" %>
  </div>
<% end %>

app/views/trait_types/show.html.erb
<h1>Trait Type #<%= @trait_type.id %></h1>

<p>
  <b>Name:</b>
  <%= @trait_type.name %>
</p>

<p>
  <b>Image url:</b>
  <%= @trait_type.image_url %>
</p>

<p>
  <b>Description:</b>
  <%= @trait_type.description %>
</p>