config/routes.rb
Beyondlife::Application.routes.draw do
  root :to => 'static#index'

  get '/sign_in' => 'sessions#new', :as => 'sign_in'
  get '/sessions' => 'sessions#create', :as => 'sessions'
  get '/sign_out' => 'sessions#destroy', :as => 'sign_out'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')

  get '/guest_posts/new', controller: 'guest_posts', action: 'new', as: 'new_guest_post'
  post '/guest_posts', controller: 'guest_posts', action: 'create'

  get '/guest_posts', controller: 'guest_posts', action: 'index', as: 'guest_posts'
  get '/guest_posts/:id', controller: 'guest_posts', action: 'show', as: 'guest_post'

  get '/guest_posts/:id/edit', controller: 'guest_posts', action: 'edit', as: 'edit_guest_post'
  put '/guest_posts/:id', controller: 'guest_posts', action: 'update'

  delete '/guest_posts/:id', controller: 'guest_posts', action: 'destroy'

  get '/trait_types/new', controller: 'trait_types', action: 'new', as: 'new_trait_type'
  post '/trait_types', controller: 'trait_types', action: 'create'

  get '/trait_types', controller: 'trait_types', action: 'index', as: 'trait_types'
  get '/trait_types/:id', controller: 'trait_types', action: 'show', as: 'trait_type'

  get '/trait_types/:id/edit', controller: 'trait_types', action: 'edit', as: 'edit_trait_type'
  put '/trait_types/:id', controller: 'trait_types', action: 'update'

  delete '/trait_types/:id', controller: 'trait_types', action: 'destroy'

  get '/traits/new', controller: 'traits', action: 'new', as: 'new_trait'
  post '/traits', controller: 'traits', action: 'create'

  get '/traits', controller: 'traits', action: 'index', as: 'traits'
  get '/traits/:id', controller: 'traits', action: 'show', as: 'trait'

  get '/traits/:id/edit', controller: 'traits', action: 'edit', as: 'edit_trait'
  put '/traits/:id', controller: 'traits', action: 'update'

  delete '/traits/:id', controller: 'traits', action: 'destroy'

  get '/people/new', controller: 'people', action: 'new', as: 'new_person'
  post '/people', controller: 'people', action: 'create'

  get '/people', controller: 'people', action: 'index', as: 'people'
  get '/people/:id', controller: 'people', action: 'show', as: 'person'

  get '/people/:id/edit', controller: 'people', action: 'edit', as: 'edit_person'
  put '/people/:id', controller: 'people', action: 'update'

  delete '/people/:id', controller: 'people', action: 'destroy'

  get '/users/new', controller: 'users', action: 'new', as: 'new_user'
  post '/users', controller: 'users', action: 'create'

  get '/users', controller: 'users', action: 'index', as: 'users'
  get '/users/:id', controller: 'users', action: 'show', as: 'user'

  get '/users/:id/edit', controller: 'users', action: 'edit', as: 'edit_user'
  put '/users/:id', controller: 'users', action: 'update'

  delete '/users/:id', controller: 'users', action: 'destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :people
  has_many :guest_posts


  def self.from_omniauth(auth)
  where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    create! do |user|
      user.access_token = auth.credentials.token
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.full_name = auth.info.name
      user.email = auth.info.email
      user.avatar = auth.info.image
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.full_name = params[:full_name]
    @user.email = params[:email]
    @user.uid = params[:uid]
    @user.access_token = params[:access_token]
    @user.provider = params[:provider]
    @user.avatar = params[:avatar]
    
    if @user.save
            redirect_to users_url
          else
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.first_name = params[:first_name]
    @user.last_name = params[:last_name]
    @user.full_name = params[:full_name]
    @user.email = params[:email]
    @user.uid = params[:uid]
    @user.access_token = params[:access_token]
    @user.provider = params[:provider]
    @user.avatar = params[:avatar]
    
    if @user.save
            redirect_to users_url
          else
      render 'edit'
    end
  end

  def destroy
    @user = User.find_by_id(params[:id])
    @user.destroy
        redirect_to users_url
      end
end

app/views/users/edit.html.erb
<h1>Editing User #<%= @user.id %></h1>


<%= form_tag(user_url(@user), method: 'put') do %>

  <div>
    <%= label_tag :first_name %><br />
    <%= text_field_tag :first_name, @user.first_name %>
  </div>

  <div>
    <%= label_tag :last_name %><br />
    <%= text_field_tag :last_name, @user.last_name %>
  </div>

  <div>
    <%= label_tag :full_name %><br />
    <%= text_field_tag :full_name, @user.full_name %>
  </div>

  <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, @user.email %>
  </div>

  <div>
    <%= label_tag :uid %><br />
    <%= number_field_tag :uid, @user.uid %>
  </div>

  <div>
    <%= label_tag :access_token %><br />
    <%= text_field_tag :access_token, @user.access_token %>
  </div>

  <div>
    <%= label_tag :provider %><br />
    <%= text_field_tag :provider, @user.provider %>
  </div>

  <div>
    <%= label_tag :avatar %><br />
    <%= text_field_tag :avatar, @user.avatar %>
  </div>

  
  <div>
    <%= submit_tag "Update User" %>
  </div>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<p><%= link_to 'Add a New User', new_user_url %></p>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Full name</th>
      <th>Email</th>
      <th>Uid</th>
      <th>Access token</th>
      <th>Provider</th>
      <th>Avatar</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.full_name %></td>
      <td><%= user.email %></td>
      <td><%= user.uid %></td>
      <td><%= user.access_token %></td>
      <td><%= user.provider %></td>
      <td><%= user.avatar %></td>
  
      <td><%= link_to 'Show', user_url(user) %></td>
      <td><%= link_to 'Edit', edit_user_url(user) %></td>
      <td><%= link_to 'Destroy', user_url(user), method: 'delete', data: { confirm: "Do you really want to delete this user?" } %></td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>


<%= form_tag(users_url, method: 'post') do %>


  <div>
    <%= label_tag :first_name %><br />
    <%= text_field_tag :first_name %>
  </div>

    <div>
    <%= label_tag :last_name %><br />
    <%= text_field_tag :last_name %>
  </div>

    <div>
    <%= label_tag :full_name %><br />
    <%= text_field_tag :full_name %>
  </div>

    <div>
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

    <div>
    <%= label_tag :uid %><br />
    <%= number_field_tag :uid %>
  </div>

    <div>
    <%= label_tag :access_token %><br />
    <%= text_field_tag :access_token %>
  </div>

    <div>
    <%= label_tag :provider %><br />
    <%= text_field_tag :provider %>
  </div>

    <div>
    <%= label_tag :avatar %><br />
    <%= text_field_tag :avatar %>
  </div>

  
  <div>
    <%= submit_tag "Create User" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>User #<%= @user.id %></h1>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>Full name:</b>
  <%= @user.full_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Uid:</b>
  <%= @user.uid %>
</p>

<p>
  <b>Access token:</b>
  <%= @user.access_token %>
</p>

<p>
  <b>Provider:</b>
  <%= @user.provider %>
</p>

<p>
  <b>Avatar:</b>
  <%= @user.avatar %>
</p>